/quad_convex_mpc_publisher:
  ros__parameters:
    N_MPC: 5
    Q_scale: 1000.0
    mpc_dt: 0.025
    mass: 12.0
    JOINT_TORQUE_PUBLISH_RATE_MS: 15
    MPC_STATE_UPDATE_RATE_MS: 15
    mu_static_friction: 0.5
    Q_diag: [5.0, 12.0, 0.1, 50.0, 25.0, 60.0, 0.1, 0.1, 0.001, 0.1, 0.1, 2.0, 0.0]
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false

