/quad_convex_mpc_publisher:
  ros__parameters:
    N_MPC: 10
    Q_scale: 1E2
    mpc_dt: 0.025
    mass: 8.0
    Q_diag: [1.0, 1.0, 1.0, 50.0, 1.0, 50.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false

