/quad_convex_mpc_publisher:
  ros__parameters:
    N_MPC: 10
    Q_scale: 500.0
    mpc_dt: 0.025
    mass: 12.0
    Q_diag: [1.0, 10.0, 1.0, 1.0, 0.0, 30.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false

